apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rep
spec:
  replicas: 3
  selector:
    app: webui              # must match with one of pod labels
    version: "2.1"  # can be multiple, if multiple labels then selector uses "AND" condition
  template:                 # pod template
    metadata:
      name: nginx-pod
      labels:               # pod labels
        app: webui      
        version: "2.1"   # can have multiple lables
    spec:
      containers:
        - name: nginx-container
          image: nginx