apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-stateful
spec:
  replicas: 8
  serviceName: sf-service
  podManagementPolicy: Parallel # OrderedReady # optional
  selector:
    matchLabels:
      app: webui
  template:                 # pod template
    metadata:
      name: nginx-pod
      labels:               # pod labels
        app: webui      
    spec:
      containers:
        - name: web
          image: nginx:1.15